name: Build Alfred Workflow

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: composer install --apcu-autoloader
      - name: Build Alfred Workflow
        id: alfred_builder
        uses: mperezi/build-alfred-workflow@v1
        with:
          workflow_dir: .
          exclude_patterns: '.git/* .gitignore .github/*'
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Alfred Workflow
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ steps.alfred_builder.outputs.workflow_file }}
          asset_name: ${{ steps.alfred_builder.outputs.workflow_file }}
          asset_content_type: application/zip
